### ISSUE TITLE
How to make WhatsApp to recognize the same sticker pack and just update it

### ISSUE THREAD

**Issue by DrAma999** [WhatsApp/stickers#760]
**Specifications**  
OS Version: iOS 14.4
Device Manufacturer: Apple

**Stickers**
- [ x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ x] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
This is more an improvement than an issue.
On my application I would like to give users the opportunity to create animated sticker and add them to a specific sticker pack. My application basically create a "triggered" version of you selfies then you can share the video, the image, or an animated sticker from the video.
Everything works except that I've found some constraints very restrictive for my use cases.

1. A sticker pack must have at least 3 stickers. Since my sticker is generated at runtime from just one picture the only solution at the moment is to replicate the same sticker for three times.
2. Even if the sticker pack has the same name, same identifier as another one created before whatsapp recognizes it as a new one resulting in a new sticker pack each time a user want to share its sticker.

Considering that I'm wondering if there is a way to just share ONE sticker and a way to just update a sticker pack if the name and the identifier are the same.

**Reproduction Steps**  
Share a sticker pack multiple times

**Head of Commit**
master 14ca950

Best Andrea

**Comment by simonzhexu** [comment]
I think there was a bug with WhatsApp iOS app, where an update is being treated as a new pack, it is now fixed. Please upgrade your WhatsApp and try again.

**Comment by DrAma999** [comment]
@simonzhexu Updated right now, but still present... it creates a different sticker pack.
Best,
Andrea

**Comment by simonzhexu** [comment]
What is your WhatsApp app version?

**Comment by DrAma999** [comment]
It's the I guess is the latest since I have no pending updates: 
iOS 14.4.2 iPhone 12 pro
2.21.60.16

**Comment by gamya19** [comment]
Ya

**Comment by simonzhexu** [comment]
Our iOS Engineer is working on this. It will be fixed.

**Comment by AlmightyBeaver** [comment]
Any news on this? The problem still exists.
